
package hw5.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.1
 * Wed Mar 23 14:51:33 CET 2022
 * Generated source version: 3.5.1
 */

@XmlRootElement(name = "ValidatePaymentResponse", namespace = "http://hw5/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidatePaymentResponse", namespace = "http://hw5/")

public class ValidatePaymentResponse {

    @XmlElement(name = "return")
    private boolean _return;

    public boolean getReturn() {
        return this._return;
    }

    public void setReturn(boolean new_return)  {
        this._return = new_return;
    }

}

