<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="BankService" targetNamespace="http://hw5/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://hw5/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://hw5/" schemaLocation="bank_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="GetBalance">
    <wsdl:part name="parameters" element="tns:GetBalance">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ValidatePaymentResponse">
    <wsdl:part name="parameters" element="tns:ValidatePaymentResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetBalanceResponse">
    <wsdl:part name="parameters" element="tns:GetBalanceResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ValidatePayment">
    <wsdl:part name="parameters" element="tns:ValidatePayment">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Runner">
    <wsdl:operation name="GetBalance">
      <wsdl:input name="GetBalance" message="tns:GetBalance">
    </wsdl:input>
      <wsdl:output name="GetBalanceResponse" message="tns:GetBalanceResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ValidatePayment">
      <wsdl:input name="ValidatePayment" message="tns:ValidatePayment">
    </wsdl:input>
      <wsdl:output name="ValidatePaymentResponse" message="tns:ValidatePaymentResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BankServiceSoapBinding" type="tns:Runner">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GetBalance">
      <soap:operation soapAction="urn:GetBalance" style="document"/>
      <wsdl:input name="GetBalance">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GetBalanceResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ValidatePayment">
      <soap:operation soapAction="urn:ValidatePayment" style="document"/>
      <wsdl:input name="ValidatePayment">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="ValidatePaymentResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BankService">
    <wsdl:port name="BankPort" binding="tns:BankServiceSoapBinding">
      <soap:address location="http://localhost:8080/hw5/services/BankPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
