
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package soap02;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-23T14:26:14.844+01:00
 * Generated source version: 3.5.1
 *
 */

@javax.jws.WebService(
                      serviceName = "BankServiceService",
                      portName = "BankServicePort",
                      targetNamespace = "http://soap02/",
                      wsdlLocation = "	http://127.0.0.1:8000/BankService?wsdl",
                      endpointInterface = "soap02.IBankService")

public class BankServicePortImpl implements IBankService {

    private static final Logger LOG = Logger.getLogger(BankServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see soap02.IBankService#validatePayment(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.Integer arg3)*
     */
    public boolean validatePayment(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.Integer arg3) {
        LOG.info("Executing operation validatePayment");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see soap02.IBankService#getBalance(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2)*
     */
    public int getBalance(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2) {
        LOG.info("Executing operation getBalance");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            int _return = -1724277278;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
