
package soap02;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-23T14:26:14.796+01:00
 * Generated source version: 3.5.1
 *
 */
public final class IBankService_BankServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap02/", "BankServiceService");

    private IBankService_BankServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BankServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BankServiceService ss = new BankServiceService(wsdlURL, SERVICE_NAME);
        IBankService port = ss.getBankServicePort();

        {
        System.out.println("Invoking validatePayment...");
        java.lang.String _validatePayment_arg0 = "1234567890";
        java.lang.String _validatePayment_arg1 = "02/22";
        java.lang.String _validatePayment_arg2 = "143";
        java.lang.Integer _validatePayment_arg3 = 5;
        boolean _validatePayment__return = port.validatePayment(_validatePayment_arg0, _validatePayment_arg1, _validatePayment_arg2, _validatePayment_arg3);
        System.out.println("validatePayment.result=" + _validatePayment__return);


        }
        {
        System.out.println("Invoking getBalance...");
        java.lang.String _getBalance_arg0 = "1234567890";
        java.lang.String _getBalance_arg1 = "02/22";
        java.lang.String _getBalance_arg2 = "143";
        int _getBalance__return = port.getBalance(_getBalance_arg0, _getBalance_arg1, _getBalance_arg2);
        System.out.println("getBalance.result=" + _getBalance__return);


        }

        System.exit(0);
    }

}
